### ISSUE TITLE
Lack of sensor documentation

### ISSUE THREAD

**Issue by egormanga** [zschroeder6212/tiny-i2c-spi#2]
I'm a relatively experienced system software developer and hardware enthusiast. I'd like to help with the development of a libfprint driver for this project (PinePhone fingerprint sensor case), but there's no actual datasheet for the SPI protocol available out there. I've been told it's solely your project. So, assuming that you've got documentation for the sensor you picked, could you kindly share it, so people like me could contribute to the development?

**Comment by zschroeder6212** [comment]
I would love the help especially with the drivers. This is definitely not just my project however, and I collaborated with Pine64 to source the sensor and design the back cover enclosure. I've reached out to make sure that the company has not stipulated any limitations on sharing the documentation. I will post back when I know more.

**Comment by zschroeder6212** [comment]
[command spec EN.pdf](https://github.com/zschroeder6212/tiny-i2c-spi/files/7996765/command.spec.EN.pdf)
Here is the protocol documentation. It should also be on the wiki soon enough. The other docs are already there
